import Navbar from "@/components/layout/Navbar";
import { Toaster } from "@/components/ui/toaster";
import QueryClientProviderCustom from "@/providers/QueryClientProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryClientProviderCustom>
        <body className={inter.className}>
          <Navbar />
          {children}

          <Toaster />
        </body>
      </QueryClientProviderCustom>
    </html>
  );
}
